name: TntRun
main: ru.boomearo.tntrun.TntRun
version: 0.1
author: BoomEaro
description: tntrun
api-version: 1.13
depend: [ FastAsyncWorldEdit, GameControl, Board, ServerUtils ]
commands:
  tntrun:
    usage: /tntrun
    aliases: [ tr ]
    description: tntrun